### ISSUE TITLE
Exported decks are not assigned correctly by Mochi

### ISSUE THREAD

**Issue by Cutuchiqueno** [kalbetredev/mochi-cards-exporter#1]
When I have a deck in Mochi with the name *Math* and I export from a file within Obsidian that has `deck: Math` in the yaml header this deck is not assigned to the Mochi deck correctly after import. Instead a second deck with name *Math* is created. Even if I import the same deck a second time a third deck with the same name is created.

Is there any way to have the exported cards into an existing Mochi deck? Maybe by using the Mochi deck id instead of a deck name in Obsidian?

**Comment by ghost** [comment]
This is an expected behavior since the exported deck will be assigned a new id by Mochi when you import them. Mochi uses ids not names to identify decks.

When you export decks from obsidian they are not assigned ids. The id assignment automatically happens when importing.

Besides, the issue with importing a deck that has the same id as a deck in Mochi is that the import will fail due to id conflict rather than merging the decks. This was the reason I didn't pre-assign an id during exporting.

**Comment by Cutuchiqueno** [comment]
Ok, thx for the info and the plugin!
